/**
 * Generates a PDF compliance report for a scan using pdfkit.
 * Language is carefully neutral: "AI Observation" / "Requires Human
 * Verification" / "Human Review Decision" - never "violation" or "illegal".
 */
const PDFDocument = require('pdfkit');

const STATUS_LABEL = {
  ok: 'No Issue Observed',
  possible_issue: 'Possible Issue',
  missing_mandatory_declaration: 'Missing Mandatory Declaration',
  requires_human_verification: 'Requires Human Verification',
};

function generateComplianceReportPdf({ scan, extractedFields, observations, summary, humanReview }) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks = [];
  doc.on('data', (c) => chunks.push(c));

  const done = new Promise((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });

  // --- Header ---
  doc.fontSize(18).text('Legal Metrology Compliance Report (PoC)', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(9).fillColor('#666')
    .text('Generated by an automated PoC tool. This report contains AI Observations only and is NOT a legal determination of compliance or non-compliance.', { align: 'center' });
  doc.fillColor('#000').moveDown();

  doc.fontSize(11);
  doc.text(`Scan ID: ${scan.id}`);
  doc.text(`Date generated: ${new Date().toLocaleString('en-IN')}`);
  doc.text(`Original filename: ${scan.original_filename || 'N/A'}`);
  doc.moveDown();

  // --- Section 1: OCR Extracted Data ---
  sectionHeader(doc, '1. OCR Extracted Data');
  const fieldRows = [
    ['Manufacturer / Packer / Importer', extractedFields.manufacturer_name],
    ['Manufacturer Address', extractedFields.manufacturer_address],
    ['Country of Origin', extractedFields.country_of_origin],
    ['Commodity Name', extractedFields.commodity_name],
    ['Net Quantity', extractedFields.net_quantity_value ? `${extractedFields.net_quantity_value} ${extractedFields.net_quantity_unit || ''}` : null],
    ['Manufacture Date', extractedFields.mfg_date],
    ['Best Before / Use By', extractedFields.best_before_date],
    ['MRP', extractedFields.mrp_raw],
    ['Unit Sale Price', extractedFields.unit_sale_price_raw],
    ['Consumer Care', [extractedFields.consumer_care_name, extractedFields.consumer_care_phone, extractedFields.consumer_care_email].filter(Boolean).join(' | ')],
    ['OCR Confidence', extractedFields.ocr_confidence != null ? `${Math.round(extractedFields.ocr_confidence * 100)}%` : 'N/A'],
  ];
  fieldRows.forEach(([label, value]) => {
    doc.fontSize(10).fillColor('#333').text(`${label}: `, { continued: true }).fillColor('#000').text(value || 'Not detected');
  });
  doc.moveDown();

  // --- Section 2: Rule Engine Assessment ---
  sectionHeader(doc, '2. Rule Engine Assessment (AI Observations)');
  doc.fontSize(9).fillColor('#666').text(
    `Summary: ${summary.ok} field(s) appear present, ${summary.possible_issues} possible issue(s), ${summary.requires_verification} requiring human verification.`
  );
  doc.fillColor('#000').moveDown(0.5);

  observations.forEach((obs) => {
    doc.fontSize(10.5).fillColor('#111').text(`[${obs.rule_id}] ${obs.title}`, { continued: true });
    doc.fillColor(colorForStatus(obs.status)).text(`  —  ${STATUS_LABEL[obs.status] || obs.status}`);
    doc.fillColor('#000').fontSize(9).text(`Legal reference: ${obs.legal_reference}`);
    doc.text(obs.ai_message);
    if (obs.recommendation) doc.fillColor('#444').text(`Recommendation: ${obs.recommendation}`).fillColor('#000');
    doc.moveDown(0.5);
  });

  // --- Section 3: Human Review Decision ---
  sectionHeader(doc, '3. Human Review Decision');
  if (humanReview && humanReview.reviewed) {
    doc.fontSize(10).text(`Reviewed by: ${humanReview.reviewer_name || humanReview.reviewer_email || 'N/A'}`);
    doc.text(`Reviewed at: ${humanReview.reviewed_at ? new Date(humanReview.reviewed_at).toLocaleString('en-IN') : 'N/A'}`);
    doc.text(`Reviewer decision: ${humanReview.decision || 'No decision recorded'}`);
    if (humanReview.notes) doc.text(`Reviewer notes: ${humanReview.notes}`);
  } else {
    doc.fontSize(10).fillColor('#a15c00').text('This scan has not yet been reviewed by a human inspector. AI Observations above should not be treated as final.');
    doc.fillColor('#000');
  }

  doc.moveDown();
  doc.fontSize(8).fillColor('#888').text(
    'Disclaimer: This is a Proof-of-Concept tool. It performs automated OCR extraction and rule-based checks against a configurable subset of the Legal Metrology (Packaged Commodities) Rules, 2011. It does not constitute legal advice or an official compliance certificate.',
    { align: 'left' }
  );

  doc.end();
  return done;
}

function sectionHeader(doc, text) {
  doc.moveDown(0.3);
  doc.fontSize(13).fillColor('#000').text(text);
  doc.moveTo(doc.x, doc.y).lineTo(545, doc.y).strokeColor('#ccc').stroke();
  doc.moveDown(0.3);
}

function colorForStatus(status) {
  switch (status) {
    case 'ok': return '#1a7f37';
    case 'possible_issue': return '#b35900';
    case 'missing_mandatory_declaration': return '#b30000';
    case 'requires_human_verification': return '#8a6d00';
    default: return '#000';
  }
}

module.exports = { generateComplianceReportPdf };
