/**
 * Generates a PDF compliance report for a scan using pdfkit.
 * Language is carefully neutral: "AI Observation" / "Requires Human
 * Verification" / "Human Review Decision" - never "violation" or "illegal".
 *
 * Upgraded for Gemini-first pipeline: adds OCR section with engine, fallback,
 * confidence, warnings, conflicts, evidence, and preserves three-stage concept.
 */
const PDFDocument = require('pdfkit');

const STATUS_LABEL = {
  ok: 'No Issue Observed',
  possible_issue: 'Possible Issue',
  missing_mandatory_declaration: 'Missing Mandatory Declaration',
  requires_human_verification: 'Requires Human Verification',
  not_found: 'Not Found',
  unreadable: 'Unreadable',
  not_applicable: 'Not Applicable',
  conflicting: 'Conflicting',
  verified: 'Verified',
};

function generateComplianceReportPdf({ scan, extractedFields, observations, summary, humanReview }) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks = [];
  doc.on('data', (c) => chunks.push(c));

  const done = new Promise((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });

  // --- Header ---
  doc.fontSize(18).text('Legal Metrology Compliance Report (PoC)', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(9).fillColor('#666')
    .text('Generated by an automated PoC tool. This report contains AI Observations only and is NOT a legal determination of compliance or non-compliance. Gemini extracts evidence; the deterministic rule engine evaluates it; the human inspector remains final authority.', { align: 'center' });
  doc.fillColor('#000').moveDown();

  doc.fontSize(11);
  doc.text(`Scan ID: ${scan.id}`);
  doc.text(`Date generated: ${new Date().toLocaleString('en-IN')}`);
  doc.text(`Original filename: ${scan.original_filename || 'N/A'}`);
  if (scan.images && Array.isArray(scan.images) && scan.images.length > 1) {
    doc.text(`Images in scan: ${scan.images.length} (${scan.images.map(i => i.originalname || i.image_id).join(', ')})`);
  }
  doc.moveDown();

  // --- OCR Section (new per spec 23) ---
  sectionHeader(doc, 'OCR Analysis');
  const ocrEngine = scan.ocr_engine || scan.normalized_ocr?.engine || 'unknown';
  const fallbackUsed = scan.ocr_attempts?.fallback_used ?? scan.normalized_ocr?.fallback_used ?? (ocrEngine.includes('fallback') || ocrEngine.includes('easyocr'));
  const ocrConfidence = scan.ocr_confidence ?? scan.normalized_ocr?.confidence ?? extractedFields.ocr_confidence;
  const languageDetected = scan.language_detected || scan.normalized_ocr?.language_detected || [];
  const warnings = scan.ocr_warnings || scan.normalized_ocr?.warnings || [];
  const conflicts = scan.field_conflicts || scan.normalized_ocr?.conflicts || [];
  const evidence = scan.evidence || scan.normalized_ocr?.evidence || [];

  doc.fontSize(10);
  doc.fillColor('#333').text(`Primary engine: `, { continued: true }).fillColor('#000').text(ocrEngine || 'Unknown');
  if (ocrEngine.toLowerCase().includes('gemini')) {
    doc.fillColor('#333').text(`Fallback used: `, { continued: true }).fillColor('#000').text(fallbackUsed ? 'Yes — EasyOCR' : 'No');
  } else if (ocrEngine === 'easyocr' || ocrEngine === 'fallback') {
    doc.fillColor('#333').text(`Fallback used: `, { continued: true }).fillColor('#000').text('N/A (EasyOCR primary due to Gemini unavailable)');
  }
  doc.fillColor('#333').text(`Overall OCR confidence: `, { continued: true }).fillColor('#000').text(ocrConfidence != null ? `${Math.round(ocrConfidence * 100)}%` : 'N/A');
  if (languageDetected && languageDetected.length) {
    doc.fillColor('#333').text(`Languages detected: `, { continued: true }).fillColor('#000').text(languageDetected.join(', '));
  }
  if (scan.analysis_metadata?.pipeline?.gemini?.model || scan.normalized_ocr?.analysis_metadata?.gemini_model) {
    doc.fillColor('#333').text(`Gemini model: `, { continued: true }).fillColor('#000').text(scan.analysis_metadata?.pipeline?.gemini?.model || scan.normalized_ocr?.analysis_metadata?.gemini_model);
  }
  if (scan.analysis_metadata?.pipeline?.duration_ms) {
    doc.fillColor('#333').text(`Processing time: `, { continued: true }).fillColor('#000').text(`${scan.analysis_metadata.pipeline.duration_ms} ms`);
  }
  doc.moveDown(0.5);

  if (warnings && warnings.length) {
    doc.fontSize(9).fillColor('#8a6d00').text('Warnings:');
    warnings.slice(0, 6).forEach(w => doc.fillColor('#8a6d00').text(`• ${w}`));
    doc.fillColor('#000').moveDown(0.3);
  }

  if (conflicts && conflicts.length) {
    doc.fontSize(9).fillColor('#b35900').text('Conflicts / Disagreements:');
    conflicts.slice(0, 6).forEach(c => {
      const msg = c.message || `${c.field}: ${c.gemini_value || c.values?.join(' vs ') || JSON.stringify(c)}`;
      doc.fillColor('#b35900').text(`• ${msg}`);
    });
    doc.fillColor('#000').moveDown(0.3);
  }

  if (evidence && evidence.length) {
    doc.fontSize(9).fillColor('#444').text(`Evidence blocks: ${evidence.length} extracted regions`);
    // Show first 4 evidence samples
    evidence.slice(0, 4).forEach(ev => {
      doc.fillColor('#666').fontSize(8).text(`  ${ev.field || 'unknown'}: "${(ev.raw_text || '').slice(0, 80)}" (conf ${Math.round((ev.confidence||0)*100)}%, engine ${ev.engine||ocrEngine})`);
    });
    doc.fillColor('#000').moveDown(0.5);
  }

  // --- Section 1: OCR Extracted Data ---
  sectionHeader(doc, '1. OCR Extracted Data');
  const fieldRows = [
    ['Manufacturer / Packer / Importer', extractedFields.manufacturer_name],
    ['Manufacturer Address', extractedFields.manufacturer_address],
    ['Importer', extractedFields.importer_name],
    ['Country of Origin', extractedFields.country_of_origin],
    ['Commodity Name', extractedFields.commodity_name],
    ['Net Quantity', extractedFields.net_quantity_value ? `${extractedFields.net_quantity_value} ${extractedFields.net_quantity_unit || ''}` : null],
    ['Manufacture Date', extractedFields.mfg_date],
    ['Best Before / Use By', extractedFields.best_before_date],
    ['MRP', extractedFields.mrp_raw],
    ['Unit Sale Price', extractedFields.unit_sale_price_raw],
    ['Consumer Care', [extractedFields.consumer_care_name, extractedFields.consumer_care_phone, extractedFields.consumer_care_email].filter(Boolean).join(' | ')],
    ['OCR Confidence', extractedFields.ocr_confidence != null ? `${Math.round(extractedFields.ocr_confidence * 100)}%` : 'N/A'],
  ];
  // Add per-field confidence if available from normalized_ocr
  const fieldConfidences = scan.normalized_ocr?.field_confidences || {};
  fieldRows.forEach(([label, value]) => {
    const confKeyMap = {
      'Manufacturer / Packer / Importer': 'manufacturer_name',
      'Country of Origin': 'country_of_origin',
      'Net Quantity': 'net_quantity_value',
      'Manufacture Date': 'mfg_date',
      'Best Before / Use By': 'best_before_date',
      'MRP': 'mrp_raw',
      'Consumer Care': 'consumer_care_phone',
    };
    const ck = confKeyMap[label];
    const conf = ck ? fieldConfidences[ck] : null;
    const confStr = conf != null ? ` (${Math.round(conf*100)}%)` : '';
    doc.fontSize(10).fillColor('#333').text(`${label}${confStr}: `, { continued: true }).fillColor('#000').text(value || 'Not detected');
  });
  // Show field statuses if available
  const fieldStatuses = scan.normalized_ocr?.field_statuses || {};
  const statusEntries = Object.entries(fieldStatuses).filter(([, v]) => v === 'conflicting' || v === 'requires_human_verification' || v === 'unreadable');
  if (statusEntries.length) {
    doc.moveDown(0.3);
    doc.fontSize(8).fillColor('#8a6d00').text('Fields requiring verification: ' + statusEntries.map(([k,v]) => `${k} (${v})`).join(', '));
    doc.fillColor('#000');
  }
  doc.moveDown();

  // --- Section 2: Rule Engine Assessment ---
  sectionHeader(doc, '2. Rule Engine Assessment (AI Observations)');
  doc.fontSize(9).fillColor('#666').text(
    `Summary: ${summary.ok} field(s) appear present, ${summary.possible_issues} possible issue(s), ${summary.requires_verification} requiring human verification.`
  );
  doc.fillColor('#000').moveDown(0.5);

  observations.forEach((obs) => {
    doc.fontSize(10.5).fillColor('#111').text(`[${obs.rule_id}] ${obs.title}`, { continued: true });
    doc.fillColor(colorForStatus(obs.status)).text(`  —  ${STATUS_LABEL[obs.status] || obs.status}`);
    doc.fillColor('#000').fontSize(9).text(`Legal reference: ${obs.legal_reference}`);
    doc.text(obs.ai_message);
    if (obs.recommendation) doc.fillColor('#444').text(`Recommendation: ${obs.recommendation}`).fillColor('#000');
    // Show checks detail if any failed
    if (obs.checks && obs.checks.some(c => c.passed === false)) {
      doc.fontSize(8).fillColor('#666').text('Checks: ' + obs.checks.map(c => `${c.checkName}:${c.passed ? 'pass' : 'fail'}`).join(', '));
      doc.fillColor('#000');
    }
    doc.moveDown(0.5);
  });

  // --- Section 3: Human Review Decision ---
  sectionHeader(doc, '3. Human Review Decision');
  if (humanReview && humanReview.reviewed) {
    doc.fontSize(10).text(`Reviewed by: ${humanReview.reviewer_name || humanReview.reviewer_email || 'N/A'}`);
    doc.text(`Reviewed at: ${humanReview.reviewed_at ? new Date(humanReview.reviewed_at).toLocaleString('en-IN') : 'N/A'}`);
    doc.text(`Reviewer decision: ${humanReview.decision || 'No decision recorded'}`);
    if (humanReview.notes) doc.text(`Reviewer notes: ${humanReview.notes}`);
  } else {
    doc.fontSize(10).fillColor('#a15c00').text('This scan has not yet been reviewed by a human inspector. AI Observations above should not be treated as final.');
    doc.fillColor('#000');
  }

  // Show correction history if any
  if (scan.correction_history && scan.correction_history.length) {
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor('#666').text(`Corrections: ${scan.correction_history.length} human correction(s) recorded. Last at ${scan.correction_history[scan.correction_history.length-1].corrected_at}`);
    doc.fillColor('#000');
  }

  doc.moveDown();
  doc.fontSize(8).fillColor('#888').text(
    'Disclaimer: This is a Proof-of-Concept tool. It performs automated OCR extraction and rule-based checks against a configurable subset of the Legal Metrology (Packaged Commodities) Rules, 2011. It does not constitute legal advice or an official compliance certificate. OCR may be imperfect - human verification is required for any enforcement action.',
    { align: 'left' }
  );

  doc.end();
  return done;
}

function sectionHeader(doc, text) {
  doc.moveDown(0.3);
  doc.fontSize(13).fillColor('#000').text(text);
  doc.moveTo(doc.x, doc.y).lineTo(545, doc.y).strokeColor('#ccc').stroke();
  doc.moveDown(0.3);
}

function colorForStatus(status) {
  switch (status) {
    case 'ok': return '#1a7f37';
    case 'possible_issue': return '#b35900';
    case 'missing_mandatory_declaration': return '#b30000';
    case 'requires_human_verification': return '#8a6d00';
    default: return '#000';
  }
}

module.exports = { generateComplianceReportPdf };
